# Generated by Django 3.1.1 on 2020-09-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('dependants', models.IntegerField()),
                ('applicant_income', models.IntegerField()),
                ('coapplicant_income', models.IntegerField()),
                ('loan_amt', models.IntegerField()),
                ('loan_term', models.IntegerField()),
                ('credit_history', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('married', models.CharField(max_length=15)),
                ('graduated_education', models.CharField(max_length=15)),
                ('self_employed', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=15)),
            ],
        ),
    ]
